name: Deploy ChatGPT Web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: 159.75.229.92
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull anomanm/chatgpt-web
            cd docker/mygpt
            docker-compose down
            docker-compose up -d
