name: Deploy ChatGPT Web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: [build_docker]
    runs-on: ubuntu-latest
    steps:

      - name: Setup SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 159.75.229.92
          username: ${{ secrets.USERNAME }}
          fingerprint: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull anomanm/chatgpt-web
            cd docker/mygpt
            docker-compose down
            docker-compose up -d
