name: Deploy ChatGPT Web

on:
  workflow_run:
    workflows: [build_docker]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull anomanm/chatgpt-web
            cd docker/mygpt
            docker-compose down
            docker-compose up -d
